### ISSUE TITLE
Could you release the supplemental materials

### ISSUE THREAD

**Issue by csyanbin** [vt-vl-lab/iCAN#12]
iCAN is an interesting work.
In this paper, you said, "Additional results including detailed class-wise performance and error diagnosis can be found in the supplementary material".

Could you release this supplemental?

**Comment by gaochen315** [comment]
Thanks for your interests. 

I have uploaded the supplementary material to our [project webpage](https://gaochen315.github.io/iCAN/).  Please take a look.
