### ISSUE TITLE
ImportError: cannot import name cfg when running a training

### ISSUE THREAD

**Issue by BestSongEver** [vt-vl-lab/iCAN#13]
Thanx for ur excellent job!
I got a issue when i tried to run a training.
Please help me if u r willing to. @gaochen315   

I tired to run: python tools/Train_ResNet_HICO.py --num_iteration 1800000  but got this information:
--------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/Train_ResNet_HICO.py", line 21, in <module>
    from models.train_Solver_HICO import train_net
  File "/home/ydm/project-HOI/iCAN/tools/../lib/models/train_Solver_HICO.py", line 12, in <module>
    from ult.ult import Get_Next_Instance_HO_Neg_HICO
  File "/home/ydm/project-HOI/iCAN/tools/../lib/ult/ult.py", line 22, in <module>
    from config import cfg
ImportError: cannot import name cfg

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

I set my environment as u said and i tried tensorflow 1.1 and 1.2
-------------------------------------------------------------------------
How can i fix it?
Thanx again.

**Comment by unbiasedmodeler** [comment]
you can see from the error that the script utl.py is not able to detect the module config that is in the same directory, an easy fix would be to change line 22 in https://github.com/vt-vl-lab/iCAN/blob/master/lib/ult/ult.py  to  ``` from ult.config import cfg ``` . that should remove this error @BestSongEver

**Comment by BestSongEver** [comment]
@unbiasedmodeler   
Thanx for your reply. It works.
