### ISSUE TITLE
How to train my own dataset ?

### ISSUE THREAD

**Issue by Yi-Hu-Yueh** [vt-vl-lab/iCAN#20]
I want to detect a stealing action, such as stealing a shoe(a person put this shoe in his packet or handbag)。How many videos should I have to train ?  What is the procedure to train ?

**Comment by gaochen315** [comment]
Currently, our method doesn't support training with video input. You have to process the video frame by frame, and thus temporal information won't be taken into consideration.

**Comment by Yi-Hu-Yueh** [comment]
Can you suggest a repo that take temporal information into consideration ?
