### ISSUE TITLE
about the hico-det metrics

### ISSUE THREAD

**Issue by ZHUXUHAN** [vt-vl-lab/iCAN#22]
how do you test the hico-det and  what's your metrics?

**Comment by gaochen315** [comment]
Please refer to the HICO-DET official evaluation toolkit.

**Comment by ZHUXUHAN** [comment]
hi,do you use the detector's results to do the test for hico-det datasets?

**Comment by ZHUXUHAN** [comment]
hi man,do you select the detector's predicted boundingbox to do the test, I am confused about the problem, can you answer it? I will pay the highest respect

**Comment by gaochen315** [comment]
Hi, we ran the Faster R-CNN on HICO-DET test split. Then we paired each detected human and object to form an H-O pair, and made the HOI prediction. Thus, there is no GT used. 

Hope this helps.
