### ISSUE TITLE
detection AP

### ISSUE THREAD

**Issue by YueLiao** [vt-vl-lab/iCAN#24]
Hi，
I would like to know the detector performance on HICO-Det dataset. Could you report the AP?
On HICO-DET dataset, the same object may be annotated by several bouding-boxes which have high IOU with each other. I wonder if you have done something for it, when training the detector.

**Comment by gaochen315** [comment]
I didn't finetune the object detector on HICO-DET at all. I used the off-the-shelf Detectron with ResNet-50-FPN backbone and performed the object detection on the testing split.

I also noticed that some objects were annotated several times. I merge the bounding boxes if they 1) have an IOU higher than 0.6 and 2) have the same object categories. 

Hope this helps.

**Comment by YueLiao** [comment]
I got it. Thanks for your reply.
