### ISSUE TITLE
About Trainval_Neg_VCOCO.pkl

### ISSUE THREAD

**Issue by shadowclouds** [vt-vl-lab/iCAN#26]
May i ask what's the meaning of the data in Trainval_Neg_VCOCO.pkl?
The data in Trainval_GT_VCOCO.pkl is the groundtruth of the bounding box,but i don't know what's the meaning of the data in Trainval_Neg_VCOCO.pkl

**Comment by gaochen315** [comment]
Hi,

Trainval_Neg_VCOCO.pkl contains negative examples I need to train the network. You can refer to #4 for more details.
