### ISSUE TITLE
Test Time

### ISSUE THREAD

**Issue by karenyun** [vt-vl-lab/iCAN#28]
Hi @gaochen315, thanks for the great work. 

I have a question about the test time. If we assume that there are m persons and n objects, so the test_net need to process N=m*(m+n-1) times, and N might be very large, how much time do you use when testing?

Since I have not run your code yet, but when I do it on my own with pytorch it will cost much time.

Thanks a lot!

**Comment by gaochen315** [comment]
Did you batch process these m*(m+n-1) pairs, or you detect the HOI for each pair independently? I recall it takes me less than 1 second to process one HICO-DET testing image.

**Comment by karenyun** [comment]
Hi, thanks!
Do you only use 1s for the whole m*(m+n-1) pairs? If it is, it seems reasonable about the time. Thanks very much!

**Comment by finngaida** [comment]
@karenyun Did you end up writing a Pytorch version of the network?
