### ISSUE TITLE
from __future__ import divisions

### ISSUE THREAD

**Issue by youjiangxu** [vt-vl-lab/iCAN#3]
when running the code, it reports that:
```
 File "tools/Train_ResNet_VCOCO.py", line 20, in <module>
    from ult.config import cfg
SyntaxError: future feature divisions is not defined (config.py, line 8)
```

And I update the `from __future__ import divisions` of `config.py` with:
`from __future__ import division`

and solve this error. it seems a typo error of `lib/ult/config.py`.

**Comment by gaochen315** [comment]
Good catch! 
It is fixed. Thanks.
