### ISSUE TITLE
visualizing the attention maps

### ISSUE THREAD

**Issue by BestSongEver** [vt-vl-lab/iCAN#35]
Thanks for sharing your code. @gaochen315
I wonder how can i successfully visualize the attention maps like those in your paper?
Could anyone help? Thanx a lot.

**Comment by gaochen315** [comment]
You can use the following command: `O_att = gray2rgb(O_att, cmap='jet')`

**Comment by chentairan** [comment]
Hi GaoChen, 

I have the same problem, can you give me some detailed tips

Thanks,
Tairan Chen
