### ISSUE TITLE
No prior_mask.pkl file and no detection on Djokovic image

### ISSUE THREAD

**Issue by aditya-droid** [vt-vl-lab/iCAN#36]
Hi, 
Thanks for the awesome work that you are doing. I am really impressed with the way the model works out. However, when testing the custom images steps, I did all the steps correctly. Also, I guess both the object detection and HOI detection commands were successful without any errors. However, when trying to demo the Djokovic image I get no bounding boxes and no HOI detections. 

There was no prior_mask.pkl and action_index.json files. I downloaded them from your drive and placed them in the Data folder in order to run the model on the Djokovic images. 

I guess the error is because of prior_mask.pkl file? But I'm not sure. Can you help out?

**Comment by aditya-droid** [comment]
Nevermind, I didn't save the HOI detection.pkl file in the appropriate folder, thus resulting in this issue.

**Comment by anon112233** [comment]
Hello,
I have the same issue and are wondering how you fixed it. I put the Object_Detection.pkl file in the right folder but the prior_mask.pkl does seem necessary.

**Comment by aditya-droid** [comment]
I had the prior_mask.pkl downloaded and being used. Did you download it and placed in the appropriate path?
