### ISSUE TITLE
About negative samples

### ISSUE THREAD

**Issue by Siyuan-Zhou** [vt-vl-lab/iCAN#4]
Hi, what do the rear three elements in each list in  'Trainval_Neg_HICO.pkl' mean?
for example, 
[
	2, # image_id
	53, # action_HO, negative HOI
	array([257.58002 ,   2.112835, 631.65155 , 128.04715 ], dtype=float32), # Human bbox
	array([129.54727 ,  65.349594, 180.34726 , 148.78911 ], dtype=float32), # Object bbox
	[46, 47, 48, 49, 50, 51, 52, 53], # 1
	40, # 2
	array(0.7580195, dtype=float32) # 3
]
can you illustrate the last three elements? 

By the way, do you change the order of 80 objects  in COCO(or VCOCO)?

**Comment by gaochen315** [comment]
The 5th element is the [HOI classes](http://napoli18.eecs.umich.edu/public_html/data/hico_list_hoi.txt) that are associated with this object.
The 6th element is the object class.
The 7th element is the object detection score.

Actually, I never use these pieces of information to train the network as the Negative examples are only used to train our spatial configuration stream.

No, I don't change the order of 80 objects in COCO. However, In the HICO-DET dataset, the [object id](http://napoli18.eecs.umich.edu/public_html/data/hico_list_obj.txt) is different from the COCO object id. So I did some additional work to compensate for this mismatch. If you use the same data format as mine and the evaluation code I provided, you should be fine.

Hope this helps.

**Comment by Siyuan-Zhou** [comment]
Much thanks for your help :)

**Comment by Siyuan-Zhou** [comment]
I've been encoutered with another problem. Given detection result, how do you generate positive samples and negative ones? 

Suppose m people and n objects exist in one picture, do 'all pairs' (described in your paper) means positive and negative samples add up to m * n in all? For negative samples, how to generate according HOI number(is it random)? 

If some objects, maybe too small or some else, are not detected by detectron, do you add them manually using GT? If so, only bbox can be added, these objects have no detection score, then how to deal with it?

As object includes 'human'(object id = 1), do your 'all pairs' include pairs between all people?

Much thanks if you may answer me. So sorry to bother you for long :)

**Comment by gaochen315** [comment]
1. In training, positive examples are given by the dataset. To obtain the negative examples:
1> Detect all objects in an image
2> Pair all the Human and Object that has the score higher than a threshold
3> HO pairs that are not included in the GT, are the negative examples

2. I only use the objects detected by Faster RCNN.

3. It depends. For V-COCO, there is no H-H interaction. But for HICO-DET, H-H interactions are possible.

**Comment by Siyuan-Zhou** [comment]
In 'Trainval_GT_HICO.pkl', each sub-list of a (person, object) pair can have several positive HOI numbers. However, in HICO dataset, each pair of person and object can only have one HOI number, since bounding boxes of human and objects in HICO dataset are based on HOI numbers. 
My question is, in this file, since bounding boxes are integer based, then do you round the detection results and put them in the file, or do you transfer human and objects boxes in HICO dataset from HOI-level to image-level to make mutiple HOIs existing between one pair possible? (If is the latter one, do you combine several boxes in the dataset using IOU, to change boxes  to image_level?)

**Comment by gaochen315** [comment]
Good question.

I combine H-O pairs in an image if IOU is greater than a threshold.

**Comment by goolhanrry** [comment]
Hi @gaochen315 ! May I ask how did you generate the hoi_ids for the Neg samples?
