### ISSUE TITLE
The single category score in the output value is greater than 1

### ISSUE THREAD

**Issue by bitwangdan** [vt-vl-lab/iCAN#41]
![image](https://user-images.githubusercontent.com/18326564/77601042-9ff03400-6f44-11ea-91e3-961478560b29.png)
i used my own dataset(hico style) to train the model, There are six categories， However, during testing, the output of some categories was greater than 1。

**Comment by gaochen315** [comment]
Yea, it's possible. The final score equals (s_h + s_o) * s_sp, which is in the range of [0,2]. You can simply divide the score by 2, and it should be in [0,1].
