### ISSUE TITLE
 Visualize the attention map using heatmap

### ISSUE THREAD

**Issue by chentairan** [vt-vl-lab/iCAN#44]
Hi GaoChen,

#35 
I have the same problem, can you give me some detailed tips

Thanks,
Tairan Chen

**Comment by gaochen315** [comment]
After obtaining the attention map 
https://github.com/vt-vl-lab/iCAN/blob/752ce5bd5775af29b6ee3cea51aff602354a2317/lib/networks/iCAN_ResNet50_VCOCO.py#L320
You can color code the attention map by `O_att = gray2rgb(O_att, cmap='jet')`. Then you can either save this map or plot it for visualization.

Let me know if you have any other questions.

**Comment by chentairan** [comment]
Thanks, I have dealed with it.
