### ISSUE TITLE
How to use trained model after finishing the training

### ISSUE THREAD

**Issue by dotahmed** [vt-vl-lab/iCAN#45]
Hello, this code is very helpful. I did run the training script and I found that the model is saved with checkpoints every 20000 iterations. But, when the training if over how to use the final model in the code. I see that you use a .pkl file in Results/300000_iCAN_ResNet50_VCOCO.pkl so how I use the the new trained model.

In addition to, I need to know what do you mean by the files 
 Trainval_GT
 Trainval_N 
or what are there content?

Thank you.

**Comment by gaochen315** [comment]
Hi, which dataset did you train on? For example, If you train a late-fusion iCAN on V-COCO, and you want to use the weight obtained at 300000 iterations, you can 

`python tools/Test_ResNet_VCOCO.py --model iCAN_ResNet50_VCOCO --num_iteration 300000`

Also, you can refer to the [testing section](https://github.com/vt-vl-lab/iCAN#testing) for more information. 

Let me know if this helps.

**Comment by dotahmed** [comment]
Thank you for your reply,  how can I use the obtained weights after training? How to run the model on a custom image rather than the test images? 
I 've already run the training script and it work good.
I hope I can find comments that explain the purpose of each class and function on it.
In addition to, I need to know what do you mean by the files
Trainval_GT
Trainval_N
or what are there content?

**Comment by gaochen315** [comment]
To test on your own images, you can refer to this [section](https://github.com/vt-vl-lab/iCAN#demotest-on-your-own-images).
 
Trainval_GT is the official training data of V-COCO and HICO-DET. I change the format that iCAN recognized.
Trainval_N is the negative training data (the non-interaction). I create this data myself to further improve the performance.
