### ISSUE TITLE
Annotations for objects and verbs

### ISSUE THREAD

**Issue by BozhouZha** [vt-vl-lab/iCAN#46]
Hi there,

What your group have done is amazing! I'm trying to see the performance on the V-COCO dataset, however I wonder would there be an annotation marks the mapping between the category id and the actual meaning? some stuff like:
{"objs":
{"15": "bench",
  "19": "horse",
  "9": "boat"}
"verbs":
{"1": "sit",
  "6": "play",
  "9": "throw"}
}

I looked up the COCO official site, but only the object part is found whereas the list of verbs are missing.

I would appreciate it if you can help!

**Comment by gaochen315** [comment]
This is the mapping between the verb and its index:

{"cut_instr": 2, "snowboard_instr": 21, "cut_obj": 4, "surf_instr": 0, "skateboard_instr": 26, "kick_obj": 7, "eat_obj": 9, "carry_obj": 14, "throw_obj": 15, "eat_instr": 16, "smile": 17, "look_obj": 18, "hit_instr": 19, "hit_obj": 20, "ski_instr": 1, "run": 22, "sit_instr": 10, "read_obj": 24, "ride_instr": 5, "walk": 3, "point_instr": 23, "jump_instr": 11, "work_on_computer_instr": 8, "hold_obj": 25, "drink_instr": 13, "lay_instr": 12, "talk_on_phone_instr": 6, "stand": 27, "catch_obj": 28}

The index of the object is the same as official COCO annotation.

**Comment by BozhouZha** [comment]
> This is the mapping between the verb and its index:
> 
> {"cut_instr": 2, "snowboard_instr": 21, "cut_obj": 4, "surf_instr": 0, "skateboard_instr": 26, "kick_obj": 7, "eat_obj": 9, "carry_obj": 14, "throw_obj": 15, "eat_instr": 16, "smile": 17, "look_obj": 18, "hit_instr": 19, "hit_obj": 20, "ski_instr": 1, "run": 22, "sit_instr": 10, "read_obj": 24, "ride_instr": 5, "walk": 3, "point_instr": 23, "jump_instr": 11, "work_on_computer_instr": 8, "hold_obj": 25, "drink_instr": 13, "lay_instr": 12, "talk_on_phone_instr": 6, "stand": 27, "catch_obj": 28}
> 
> The index of the object is the same as the official COCO annotation.

Appreciate your kind help, that's really timely! Thanks alot!

**Comment by BozhouZha** [comment]
> This is the mapping between the verb and its index:
> 
> {"cut_instr": 2, "snowboard_instr": 21, "cut_obj": 4, "surf_instr": 0, "skateboard_instr": 26, "kick_obj": 7, "eat_obj": 9, "carry_obj": 14, "throw_obj": 15, "eat_instr": 16, "smile": 17, "look_obj": 18, "hit_instr": 19, "hit_obj": 20, "ski_instr": 1, "run": 22, "sit_instr": 10, "read_obj": 24, "ride_instr": 5, "walk": 3, "point_instr": 23, "jump_instr": 11, "work_on_computer_instr": 8, "hold_obj": 25, "drink_instr": 13, "lay_instr": 12, "talk_on_phone_instr": 6, "stand": 27, "catch_obj": 28}
> 
> The index of the object is the same as the official COCO annotation.

Hi, I'm so sorry to trouble you again. Could you please give me some hints where I can get the mapping of verbs of HICO? I tried to found a version of 106 verbs, but there are 117 in the dataset. Thus, I guess the one I'm using now is either wrong or obsolete.

Thank you in advance!

**Comment by BozhouZha** [comment]
For the objects part, you are right that the index of the object is the same as the offcial COCO annotation, but it seems the permutation is different though. I wonder whether this is the object list of correct order which enable your awesome project? It's from the official site and seems purely in the ascending order of the category id. 
![image](https://user-images.githubusercontent.com/61334263/86707063-24754700-c04a-11ea-81e3-aa3cfbe22c7c.png)
