### ISSUE TITLE
Prior_mask.pkl and action_index.json missing

### ISSUE THREAD

**Issue by anon112233** [vt-vl-lab/iCAN#47]
Hello,

First off, thank you for making the code public... I am excited to test the model. I followed the steps for the test demo in the repo but for some reason, I do not have the prior_mask.pkl file or the action_index.json file. Is there some way I can download these to make the demo work?

**Comment by gaochen315** [comment]
You can refer to https://github.com/vt-vl-lab/iCAN/blob/master/misc/download_training_data.sh

Option 1:
You can download them from https://drive.google.com/drive/u/1/folders/1aIYkkltzelHyh05RYve0AQW2dCe8SL2W

Option 2:
```
python lib/ult/Download_data.py 1z5iZWJsMl4hafo0u7f1mVj7A2S5HQBOD Data/action_index.json
python lib/ult/Download_data.py 1QeCGE_0fuQsFa5IxIOUKoRFakOA87JqY Data/prior_mask.pkl
```

Let me know if this helps.

**Comment by anon112233** [comment]
Thank you, this fixed it and I got it working. Awesome results!
