### ISSUE TITLE
How to generate training .pkl file? 

### ISSUE THREAD

**Issue by kaifengcai** [vt-vl-lab/iCAN#7]
Hi Chen,
When I trained an iCAN on V-COCO, the network read data from .pkl file which was downloaded from google Driver. Could you please tell me how to put the images dataset in a .pkl file? Do you have the code?

Thanks a lot.

**Comment by gaochen315** [comment]
For training, I convert the V-COCO and HICO-DET GT annotation into the format I preferred and save it as a pickle file.
For testing, I use Detectron to generate object detections and save them as a pickle file. Take a look at misc/Object_Detector.py line 100~111. 

Hope this helps.
