### ISSUE TITLE
Demo on video

### ISSUE THREAD

**Issue by sophia-wright-blue** [vt-vl-lab/iCAN#8]
Hello,

Thank you for releasing the code. On the home page, you have a demo on a video (two people talking from the Big Bang Theory). In the README, you have instructions for Demo/Test on our own images.

 Could you guide me on the process to do a demo on my own video? what are the steps to obtaining the results on an mp4 file?

Thank you,

**Comment by gaochen315** [comment]
Hi,

In order to test on your own images, you have to follow all steps in the Demo/Test on your own images section. Those are:

Clone and setup the tf-faster-rcnn repository.
Convert your video to PNG sequences and put them in demo/ folder.
Detect all objects
Detect all HOIs
Step 3 will save Object_Detection.pkl in the demo folder, step 4 will save HOI_Detection.pkl in the demo folder. Then you can use tools/Demo.ipynb to visualize all the HOI detections.

Hope this helps.

**Comment by sophia-wright-blue** [comment]
Thank you for the quick reply @gaochen315 ,to convert the video to PNG sequences, would I have to use something like ffmpeg? 

for the result, will tools/Demo.ipynb give the output as the HOI interactions on the video?

I'd like to be able to input an mp4 file and get the HOI interactions on the mp4 file, exactly as you have demonstrated on the home page and on the project page.

thank you

**Comment by gaochen315** [comment]
Yes. You need to use ffmpeg for the conversion. 

tools/Demo.ipynb will plot the images with interactions annotated. You can save the visualization instead of plotting them, and then convert the PNGs back to video.

**Comment by sophia-wright-blue** [comment]
ah, thank you @gaochen315  i get it now! last question - how do i convert the PNGs back to video? what tool do i use?

**Comment by gaochen315** [comment]
ffmpeg as well. The following function will do the job 
`ffmpeg -r 25 -f image2 -i pic%03d.png -pix_fmt yuv420p HOI.mp4`

**Comment by sophia-wright-blue** [comment]
thank you so much for the super fast reply @gaochen315 ! Looking forward to using the repo.

**Comment by sophia-wright-blue** [comment]
apologize for reopening the issue @gaochen315 . a related question - if the HOI interaction output is done only on the individual frames, does the temporal aspect of the video get considered? for example, 3D CNNs or CNN+RNN models consider the spatial and temporal aspects of videos. I hope my question is clear

**Comment by gaochen315** [comment]
Currently, we only care about frame-level interaction detection. However, jointly considering temporal information is definitely a correct direction and it's worthy to explore.

**Comment by sophia-wright-blue** [comment]
got it, if its not too much trouble, could you point me to a paper or two that does consider the temporal information as well?

**Comment by gaochen315** [comment]
https://github.com/jinwchoi/awesome-action-recognition

**Comment by Raoabdulrehman771** [comment]
@sophia-wright-blue 
Hi, I just read your conversation. Have you successfully done on with video detection?
